name: Codecov

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install node dependencies
      run: npm ci --ignore-scripts      
    
    - name: Build application with typescript
      run: npm run build
      
    # https://github.com/codecov/codecov-action
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        name: codecov-umbrella # optional
        fail_ci_if_error: false # optional (default = false)
        verbose: true # optional (default = false)